// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZf1WUdJicnraovB1uyUQJFEqxokQ518w',
    appId: '1:235748238715:web:d10389d8aff2ee3dec09de',
    messagingSenderId: '235748238715',
    projectId: 'trippo-75055',
    authDomain: 'trippo-75055.firebaseapp.com',
    databaseURL: 'https://trippo-75055-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-75055.firebasestorage.app',
    measurementId: 'G-3NCX1NRYR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefdQ-dfIQ9Xz4ty7E5RQYv-FlXMLks5Y',
    appId: '1:235748238715:android:d508b979096cbd8eec09de',
    messagingSenderId: '235748238715',
    projectId: 'trippo-75055',
    databaseURL: 'https://trippo-75055-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-75055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQ-_QDbLRBlDDosh8OUpV1bAlXdmh0-Q',
    appId: '1:235748238715:ios:481c65f17e7c5d04ec09de',
    messagingSenderId: '235748238715',
    projectId: 'trippo-75055',
    databaseURL: 'https://trippo-75055-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-75055.firebasestorage.app',
    iosBundleId: 'com.example.uberClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQ-_QDbLRBlDDosh8OUpV1bAlXdmh0-Q',
    appId: '1:235748238715:ios:481c65f17e7c5d04ec09de',
    messagingSenderId: '235748238715',
    projectId: 'trippo-75055',
    databaseURL: 'https://trippo-75055-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-75055.firebasestorage.app',
    iosBundleId: 'com.example.uberClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZf1WUdJicnraovB1uyUQJFEqxokQ518w',
    appId: '1:235748238715:web:7224b6c3624dc6f7ec09de',
    messagingSenderId: '235748238715',
    projectId: 'trippo-75055',
    authDomain: 'trippo-75055.firebaseapp.com',
    databaseURL: 'https://trippo-75055-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-75055.firebasestorage.app',
    measurementId: 'G-7HHT7P5XXF',
  );
}
